//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RmsoftControlsTestApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public double SelectedFontSize {
            get {
                return ((double)(this["SelectedFontSize"]));
            }
            set {
                this["SelectedFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedViewIndex {
            get {
                return ((int)(this["SelectedViewIndex"]));
            }
            set {
                this["SelectedViewIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SelectedDialogType {
            get {
                return ((string)(this["SelectedDialogType"]));
            }
            set {
                this["SelectedDialogType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::RmsoftControls.Dialogs.DialogButtons SelectedDialogButtons {
            get {
                return ((global::RmsoftControls.Dialogs.DialogButtons)(this["SelectedDialogButtons"]));
            }
            set {
                this["SelectedDialogButtons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Uri AppThemeResourceUri {
            get {
                return ((global::System.Uri)(this["AppThemeResourceUri"]));
            }
            set {
                this["AppThemeResourceUri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.ListDictionary AppThemeResourceUris {
            get {
                return ((global::System.Collections.Specialized.ListDictionary)(this["AppThemeResourceUris"]));
            }
            set {
                this["AppThemeResourceUris"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en-US")]
        public global::System.Globalization.CultureInfo SelectedCultureInfo {
            get {
                return ((global::System.Globalization.CultureInfo)(this["SelectedCultureInfo"]));
            }
            set {
                this["SelectedCultureInfo"] = value;
            }
        }
    }
}
